pipeline {
     agent any
     stages {
         stage('Checkout') {
             steps {
             git 'https://github.com/Q2MORY17/SSRS-Drone-Launcher-Beta'
             }
         }

         stage('Test') {
             steps {
                 sh 'python3 -m pip install flask'
                 sh 'python3 -m pip install pytest'
                 sh "python3 -m pytest -v -s test/manual/unittest/test_manual_launcher_python.py --junitxml=test/manual/unittest/testreport.xml"
             }
             post {
                     always {
                             junit  '**/test/manual/unittest/*.xml'
                            }
                   }
         }
     }
         post {
             always {
             junit '**/test/manual/unittest/*.xml'
             emailext attachLog: true, attachmentsPattern: '**/test/manual/unittest/*.xml',
             body: '', recipientProviders: [culprits()], subject:
             '$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!'
             }
     }




}
